# Generated by Django 6.0.5 on 2026-05-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g Sci-Fi, Thriller, Crime, Drama ....', max_length=150, unique=True, verbose_name='Genre Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g Avengers, Dhurandar, KGF.....', max_length=200, verbose_name='movie name')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('staring', models.CharField(help_text='e.g Salman Khan, Shahrukh Khan .....', max_length=1000, verbose_name='Actors Name')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('genre', models.ManyToManyField(to='book.genre')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
