# Generated by Django 6.0.5 on 2026-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='e.g Summer Love ...', max_length=200, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='staring',
            field=models.CharField(max_length=1000, verbose_name='Characters Name'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
