# Generated by Django 6.0.5 on 2026-05-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_card_no', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
    ]
